///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package s_train

import (
	"fmt"

	"go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *STrain {
	return new(STrain)
}

func NewQueryBuilder() *sTrainQueryBuilder {
	return new(sTrainQueryBuilder)
}

func (t *STrain) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type sTrainQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *sTrainQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *sTrainQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&STrain{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *sTrainQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&STrain{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *sTrainQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&STrain{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *sTrainQueryBuilder) First(db *gorm.DB) (*STrain, error) {
	ret := &STrain{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *sTrainQueryBuilder) QueryOne(db *gorm.DB) (*STrain, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *sTrainQueryBuilder) QueryAll(db *gorm.DB) ([]*STrain, error) {
	var ret []*STrain
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *sTrainQueryBuilder) Limit(limit int) *sTrainQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *sTrainQueryBuilder) Offset(offset int) *sTrainQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *sTrainQueryBuilder) WhereId(p mysql.Predicate, value int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereIdIn(value []int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereIdNotIn(value []int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderById(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainName(p mysql.Predicate, value string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_name", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainNameIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_name", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainNameNotIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainName(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_name "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainData(p mysql.Predicate, value string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_data", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainDataIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_data", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainDataNotIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_data", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainData(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_data "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainOrg(p mysql.Predicate, value string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_org", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainOrgIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_org", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainOrgNotIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_org", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainOrg(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_org "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainNum(p mysql.Predicate, value int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_num", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainNumIn(value []int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_num", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainNumNotIn(value []int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_num", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainNum(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_num "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainProject(p mysql.Predicate, value string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_project", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainProjectIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_project", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainProjectNotIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_project", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainProject(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_project "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainPlace(p mysql.Predicate, value string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_place", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainPlaceIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_place", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainPlaceNotIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_place", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainPlace(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_place "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainTime(p mysql.Predicate, value string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_time", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainTimeIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_time", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereTrainTimeNotIn(value []string) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "train_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByTrainTime(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "train_time "+order)
	return qb
}

func (qb *sTrainQueryBuilder) WhereDeleted(p mysql.Predicate, value int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted", p),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereDeletedIn(value []int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted", "IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) WhereDeletedNotIn(value []int32) *sTrainQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted", "NOT IN"),
		value,
	})
	return qb
}

func (qb *sTrainQueryBuilder) OrderByDeleted(asc bool) *sTrainQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted "+order)
	return qb
}
